version: '3.7'

services:
  nginx:
    image: nginx:latest
    links:
      - web
    volumes:
      - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"

  web:
    build: .
    volumes: &web-volumes
      - &app-volume .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
      - /db
    environment: &web-environment
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      APP_VERSION: 1.1
      RAILS_LOG_TO_STDOUT: 1
      RAILS_ROUTES_SCOPE: subrails
    command: ["bash", "-c", "RAILS_ENV=production bin/rails db:create && bin/rails db:migrate && bundle exec rails s -e production -b '0.0.0.0' -p 3000"]

volumes:
  bundle_cache:
